# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ffcce8b0-ba3b-499b-8afb-17d9c84f3b20'
  imageRepositoryVenta: 'venta'
  dockerfilePathVenta: '$(Build.SourcesDirectory)/venta/Dockerfile'
  imageRepositoryVista: 'vista'
  dockerfilePathVista: '$(Build.SourcesDirectory)/vista/Dockerfile'
  containerRegistry: 'llanovelascofinal.azurecr.io'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:

- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    acrsecret: pruebasjhony
  jobs:
  - job: Deploy
    displayName: Deploy to Venta
    pool: 
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)/kubernet'
    - task: KubernetesManifest@0
      inputs:
        action: 'createSecret'
        kubernetesServiceConnection: 'llano-velasco-final-default'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: '$(acrsecret)'
        dockerRegistryEndpoint: 'llanovelascofinal'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'llano-velasco-final-default'
        namespace: 'default'
        manifests: |
          $(Pipeline.Workspace)/kubernet/deployment-spring.yml
          $(Pipeline.Workspace)/kubernet/service-spring.yml
        #containers: '$(acrdevurl)/$(imageRepo):$(tag)'
        #imagePullSecrets: '$(acrsecret)'