apiVersion: v1
kind: Service
metadata:
  name: spring
  labels:
    app: spring
spec:
  ports:
    - name: spring
      port: 8080
      #nodePort: 30082
  type: LoadBalancer
  selector:
    app: spring
